[package]
name = "scheduler_bot"
version = "0.2.0"
authors = ["Philippe Nadon <phil@nadon.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8"